development:
  adapter: postgresql
  encoding: utf8
  database: money
  username: postgres
  password: '8456'
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: money
  username: postgres
  password: ENV['PG_PASS']
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: moneytest
  username: postgres
  password: '8456'
  host: localhost

